services:
  base_image:
    build: 
      context: .
      dockerfile: utils/docker/dockerfiles/base.dockerfile
    image: secshop/base:latest
  frontend: 
    build: 
      context: .
      dockerfile: utils/docker/dockerfiles/frontend.dockerfile
    image: secshop/frontend:latest
    ports:
      - 80:80
    depends_on:
      - base_image