services:
  base_image:
    build: 
      context: .
      dockerfile: utils/docker/dockerfiles/base.dockerfile
    image: secshop/base:latest
  frontend: 
    build: 
      context: .
      dockerfile: utils/docker/dockerfiles/frontend.dockerfile
    image: secshop/frontend:latest
    ports:
      - 80:80
    depends_on:
      - base_image
  product:
    build:
      context: .
      dockerfile:  utils/docker/dockerfiles/product.dockerfile
    image: secshop/product:latest
    ports:
      - 3000:3000
    depends_on:
      - base_image