services:
  base_image:
    build: 
      context: .
      dockerfile: utils/docker/dockerfiles/base.dockerfile
    image: secshop/base:latest
  
  frontend: 
    build: 
      context: .
      dockerfile: utils/docker/dockerfiles/frontend.dockerfile
    image: secshop/frontend:latest
    ports:
      - 80:80
    mem_limit: 512m
    cpus: 0.5
    depends_on:
      - base_image

  product:
    build:
      context: .
      dockerfile:  utils/docker/dockerfiles/product.dockerfile
    image: secshop/product:latest
    ports:
      - 3000:3000
    depends_on:
      - base_image 
    mem_limit: 512m
    cpus: 0.5

  auth:
    build:
      context: .
      dockerfile:  utils/docker/dockerfiles/auth.dockerfile
    image: secshop/auth:latest
    ports:
      - 4000:4000
    depends_on:
      - base_image 
    mem_limit: 512m
    cpus: 0.5

  gateway:
    build:
      context: .
      dockerfile: utils/docker/dockerfiles/gateway.dockerfile
    image: secshop/gateway:latest
    ports:
      - 8080:8080
    depends_on:
      - base_image
   mem_limit: 512m
    cpus: 0.5
